### ISSUE TITLE
InfoTripApiError: Request faild with status code 500

### ISSUE THREAD

**Issue by bkazic** [bkazic/mobis-traffic-expert#4]
InfoTrip service rejected predictions at 08:00, but accepted it at 07:00.

error: InfoTripApiError: Request faild with status code 500
    at new InfoTripApiError (E:\MobiS\mobis-traffic-expert\TrafficPrediction\InfoTrip\services.js:98:11)
    at Request._callback (E:\MobiS\mobis-traffic-expert\TrafficPrediction\InfoTrip\services.js:85:23)
    at Request.self.callback (E:\MobiS\mobis-traffic-expert\TrafficPrediction\node_modules\request\request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (E:\MobiS\mobis-traffic-expert\TrafficPrediction\node_modules\request\request.js:1063:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (E:\MobiS\mobis-traffic-expert\TrafficPrediction\node_modules\request\request.js:1009:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

![infotripapierror](https://cloud.githubusercontent.com/assets/5764852/10508290/7c0d3a16-7326-11e5-8650-735f9e8f77b1.png)

**Comment by bkazic** [comment]
This is the response from InfoTrip server.
Error: Data is Null. 
But I am almost 100%  sure, I am not sending Null.

![image](https://cloud.githubusercontent.com/assets/5764852/10517535/7ee0bc72-735d-11e5-8386-fd81dc6af8c3.png)

**Comment by bkazic** [comment]
There was a problem on InfoTrip server side. Issue is now fixed.
